@startuml

hide empty description

state Organization {
  state " " as OrganizationEntry <<entryPoint>>
  state "Departments" as Departments {
    state "Department" as Department1
    state "Department" as Department2
    state "Department" as Department3
  }
}
state Department {
  state " " as DepartmentEntry <<entryPoint>>
  state "Stations" as StationsByDepartment {
    state "Station" as StationByDepartment1
    state "Station" as StationByDepartment2
    state "Station" as StationByDepartment3
  }
}
state Station {
  state " " as StationEntry <<entryPoint>>
  state "Units" as UnitsByStation {
    state "Unit" as UnitByStation1
    state "Unit" as UnitByStation2
    state "Unit" as UnitByStation3
  }
  state "Responders" as RespondersByStation {
    state "Responder" as ResponderByStation1
    state "Responder" as ResponderByStation2
    state "Responder" as ResponderByStation3
  }
  state "Vehicles" as VehiclesByStation {
    state "Vehicle" as VehicleByStation1
    state "Vehicle" as VehicleByStation2
    state "Vehicle" as VehicleByStation3
  }
}
state Unit {
  state " " as UnitEntry <<entryPoint>>
  state "Responders" as RespondersByUnit {
    state "Responder" as ResponderByUnit1
    state "Responder" as ResponderByUnit2
    state "Responder" as ResponderByUnit3
  }
  state "Shifts" as ShiftsByUnit #red {
    state "Shift" as ShiftByUnit1 #red
    state "Shift" as ShiftByUnit2 #red
    state "Shift" as ShiftByUnit3 #red
  }
  state "Vehicles" as VehiclesByUnit {
    state "Vehicle" as VehicleByUnit1
    state "Vehicle" as VehicleByUnit2
    state "Vehicle" as VehicleByUnit3
  }
  state "Equipments" as EquipmentsByUnit {
    state "Equipment" as EquipmentByUnit1
    state "Equipment" as EquipmentByUnit2
    state "Equipment" as EquipmentByUnit3
  }
}
state Responder {
  state " " as ResponderEntry <<entryPoint>>
  state "Shifts" as ShiftsByResponder #red {
  }
  state "Skills" as SkillsByResponder {
  }
  state "Trainings" as TrainingsByResponder {
  }
}
state Vehicle {
  state " " as VehicleEntry <<entryPoint>>
}
state Equipment {
  state " " as EquipmentEntry <<entryPoint>>
}
state Training {
  state " " as TrainingEntry <<entryPoint>>
}
state Skill {
  state " " as SkillEntry <<entryPoint>>
}
state Shift #red{
  state " " as ShiftEntry <<entryPoint>>
}
state Dispatch #red {
  state " " as DispatchEntry <<entryPoint>>
  state "Missions" as Missions #red {
    state "Mission" as Mission1 #red
    state "Mission" as Mission2 #red
    state "Mission" as Mission3 #red
  }
}

state Mission #red {
  state " " as MissionEntry <<entryPoint>>
  state "Units" as UnitsByMission #red {
    state "Unit" as UnitByMission1 #red
    state "Unit" as UnitByMission2 #red
    state "Unit" as UnitByMission3 #red
  }
  state "Responders" as RespondersByMission #red {
    state "Responder" as ResponderByMission1 #red
    state "Responder" as ResponderByMission2 #red
    state "Responder" as ResponderByMission3 #red
  }
  state "Vehicles" as VehiclesByMission #red {
    state "Vehicle" as VehicleByMission1 #red
    state "Vehicle" as VehicleByMission2 #red
    state "Vehicle" as VehicleByMission3 #red
  }
}

[*] --> OrganizationEntry

Departments --> DepartmentEntry

StationsByDepartment --> StationEntry

UnitsByStation --> UnitEntry

RespondersByStation --> ResponderEntry
VehiclesByStation --> VehicleEntry

RespondersByUnit --> ResponderEntry
ShiftsByUnit --> ShiftEntry
VehiclesByUnit --> VehicleEntry
EquipmentsByUnit --> EquipmentEntry

ShiftsByResponder --> ShiftEntry
SkillsByResponder --> SkillEntry
TrainingsByResponder --> TrainingEntry

[*] -[#red]-> DispatchEntry

Missions -[#red]-> MissionEntry

UnitsByMission -[#red]-> UnitEntry

RespondersByMission -[#red]-> ResponderEntry
VehiclesByMission -[#red]-> VehicleEntry


@enduml